baseURL = "http://hourswith.expert/"
languageCode = "en-us"
title = "Hours with Experts"
theme = "book"
sectionPagesMenu = "main"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true